### PR TITLE
Added CUDA to languages.yaml

### LINKED ISSUE #902: CUDA support
### Language Name 🖊

Cuda

### Logo 📷

https://logos-download.com/wp-content/uploads/2016/10/NVIDIA_logo_R.png

Unsurprisingly, the language doesn't have its own logo so NVidia's logo is perhaps the obvious choice .

### Upstream support ✅

- [X] Does tokei already support the language in question?

### PR DESCRIPTION
**Pull request by jtmr05**
Fixes #902

### CODE REVIEW

**Comment by jtmr05** [comment]
Fixes #902

**Comment by spenserblack** [comment]
Hope you don't mind, edited your initial comment so that it would trigger the issue to be closed on merge.

**Review by spenserblack — APPROVED** [review]
Thank you! The ASCII LGTM. When the Vercel deployment is approved we can view the live preview.

**Review by spenserblack — CHANGES_REQUESTED** [review]
Oh, nevermind :laughing:

[Looks like the ASCII art exceeds our max dimensions](https://github.com/o2sh/onefetch/actions/runs/3970483023/jobs/6807339679#step:5:19).

Please make sure the ASCII art is no more than 40 characters wide.

**Comment by jtmr05** [comment]
this should do it

**Review by spenserblack — APPROVED** [review]
Even though [CUDA has been added to tokei's languages file](https://github.com/XAMPPRocky/tokei/blob/2306b8f118d2bde55712df031aa553e50ce3e599/languages.json#L283), it looks like it's not part of tokei's latest release :disappointed:

But the changes LGTM!

**Comment by spenserblack** [comment]
Linking #1152 to PRs and issues that will probably be affected.

**Comment by o2sh** [comment]
Thansk a lot @jtmr05 🎉 the final version: https://onefetch.dev/#Cuda

**Comment by jtmr05** [comment]
cheers

**Pull request merged**
