### PR TITLE
Adding OCAML ascii art

### PR DESCRIPTION
**Pull request by Vinetos**
Check if I have updated `main.rs` correctly !

### CODE REVIEW

**Comment by o2sh** [comment]
Thanks for your contribution @Vinetos 
I will check the main.rs in a bit.

However, the ascii art is way too big and "noisey"...
Plz, try and improve on it 👍 

After that, I will gladly merge the PR.

**Comment by Vinetos** [comment]
Is this better ? @o2sh

**Comment by o2sh** [comment]
I apologize for the late answer @Vinetos 
It's indeed better for the "noisey" part, unfortunately it's still too big.

You're almost there :1st_place_medal:

**Comment by Vinetos** [comment]
Gosh !
What's is a good size ? Because if I reduce too much, we cannot see anything ! 😂

**Pull request closed without merging**
