### PR TITLE
Add ability to disable info elements

### LINKED ISSUE #73: Disable info line from appearing in the output
We would like to allow users  to disable one (or many) info line(s) from appearing in the output via a command line flag:

`onefetch --disable size version`

:100:

### PR DESCRIPTION
**Pull request by mstruebing**
closes #73

I used `Options` to indicate if a information part is disabled or not.

Screenshot_2019-10-13_12-17-14
Screenshot_2019-10-13_12-14-50
Screenshot_2019-10-13_12-14-30

### CODE REVIEW

**Comment by o2sh** [comment]
Impressive stuff @mstruebing 

Few remarks :
* The info name provided shouldn't  be case sensitive (ex: `onefetch --disable sIzE` should work) --> you can check #75
* The enum of possible values should match with the one displayed (current_commit <> head, project_name <> project...), this can be confusing. By doing so, you won't have to specify the list of possible values in the help of the command.
* Don't  forget to add a little help to describe what the flag does, something like -->  Allows  you  to disable an info line from appearing in the output.

Looking forward to merge your PR :100:

**Comment by mstruebing** [comment]
Still to do: mixed case or uppercase arguments are counted as failures by clap.

Some arguments need clarification

How should I name:

`last_change`
`lines_of_code`
`dominant_language` 

I don't think that spaces are possible or a good idea. Looking for your feedback :)

**Comment by o2sh** [comment]
You're right @mstruebing 

This might not be optimal but here is a suggestion.
You can change the display names as such:
* Lines of code --> LOC
* Last change --> Last
* dominant_language --> language

In the same spirit, if there is only one author. The display name is gonna be just "author" --> it should be added as a possible value for the flag.

:100:

**Comment by mstruebing** [comment]
I think I've respected every change request :)

**Comment by o2sh** [comment]
when I do `onefetch --disable language`, I get this:

DeepinScreenshot_select-area_20191013225109

indeed, `Info:language` is used in get_ascii() to return the corresponding asset --> you cannot assign it to None

**Comment by mstruebing** [comment]
Thanks for you catchy eye, will fix sonnish :)

**Comment by o2sh** [comment]
I've decided to merge #82, hope you don't mind... :pray:

**Pull request closed without merging**
