### PR TITLE
Fix compilation error on linux

### PR DESCRIPTION
**Pull request by spenserblack**
I was getting a compilation error when attempting to compile on Linux.
I tested this on both Windows and Linux, compiles on both. Will probably fail on MacOS, though.

Thanks for adding me as a collaborator, @o2sh!

### CODE REVIEW

**Comment by o2sh** [comment]
You can check [this](https://github.com/rivy/rust.tin-summer/commit/a8c8bd9c5d246157e75d30b3d3ab910a1e79bcce)

This will only apply to windows

**Comment by spenserblack** [comment]
Thanks! I used a combination of the example you provided and `ansi_term`'s documentation to add this.

**Comment by spenserblack** [comment]
Do you mind if I update `.travis.yml` to compile on both Linux and Windows (and possibly OSX)?

**Comment by o2sh** [comment]
> Do you mind if I update `.travis.yml` to compile on both Linux and Windows (and possibly OSX)?

Sure 👍

**Comment by spenserblack** [comment]
Travis CI is currently pointing to a cancelled build due to a force push. But [this build](https://travis-ci.org/o2sh/onefetch/builds/599191962) should effectively be the same.

**Comment by o2sh** [comment]
Sure go ahead, it  should fix #90

**Pull request merged**
