### PR TITLE
Delete default.nix

### PR DESCRIPTION
**Pull request by filalex77**
After https://github.com/NixOS/nixpkgs/pull/74191 gets merged, these files may no longer be necessary.

cc @Kloenk

---
This change is [Reviewable](https://reviewable.io/reviews/o2sh/onefetch/170)

### CODE REVIEW

**Comment by jonringer** [comment]
it may still be valuable to ensure that you work with nixpkgs-unstable, personally, I would keep the default.nix

**Comment by filalex77** [comment]
@jonringer Didn't know about that. How's that done?

**Comment by jonringer** [comment]
you can do `nix build -f .` and it should try to evaluate+build your default.nix. Since `src =./.;`, it will differ from what's on nixpkgs

**Comment by filalex77** [comment]
Thanks for the input. I'll close the PR, and the discussion will remain for posterity.

**Comment by jonringer** [comment]
I wouldn't worry about it too much, the main thing to remember is that `<nixpkgs>` will pull from the channels, and this will likely be slight (or majorly) different for everyone.

If you want a lot of reproducibility, i would freeze nixpkgs at a commit, if you want to ensure that it roughly works with nixpkgs master, then I would leave as-is.

**Pull request closed without merging**
