### PR TITLE
Refactor modules into files

### LINKED ISSUE #97: [Code organization] Split main.rs into modules
As suggested in #70,
It's time to split the main.rs file into multiple files/modules.

Feel free to re-organize the code in a way that improves the navigation inside the project overall.

Thx  :100: :1st_place_medal:

### PR DESCRIPTION
**Pull request by andymac-2**
Fixes #97 

The program is split into several modules, the largest (the info module) is already logically quite simple, and it would not make much sense to split it any further in my opinion.

I may have broken something, but as far as I can tell through my testing, this refactor went quite smoothly.

It might be good to further refactor the `Info::new` method to have less arguments.

I also ran `rustfmt` on the resulting code since I'm changing pretty much every line anyway.

### CODE REVIEW

**Comment by o2sh** [comment]
Why did you remove the `truncate` test ?

The _Info_ module is indeed quite large.

Anyway, this is already quite well organized 🥇 

@andymac-2 I'll let you merge your PR after the conflicts are resolved.

Thanks again!

**Comment by andymac-2** [comment]
In response to the removal of the `truncate` test. Consider the following test:

```
assert_eq!(
    Tokens("  {1} {5}  {9} a").render(&colors_shim, 4, 10),
    "\u{1b}[37m\u{1b}[0m\u{1b}[37m\u{1b}[0m\u{1b}[37m \u{1b}[0m\u{1b}[37m a\u{1b}[0m   "
);
```

Which used to look something like...

```
assert_eq!(Tokens("  {1} {5}  {9} a").truncate(4, 10), "{1}{5} {9} a");
```

...in a previous version of the code that had a different `truncate` function. The old version is easily verifiable by a human being. The new version is basically unverifiable. I ended up copying the test values from the console (which is lazy) and trusting that it was correct. That means that the test wasn't doing anything productive: it would fail every time I would change something, even if the change happened to be correct. Thus the tests were removed. Perhaps they can be replaced with tests for the tokenizer which should be verifiable by a human.

**Comment by andymac-2** [comment]
Don't merge this just yet, I've still got to update the tests.

**Comment by andymac-2** [comment]
Okay, that should be it. The tests have been updated.

**Comment by o2sh** [comment]
@andymac-2 You seem to have gotten rid of my central_pad (and double line break at the end):

```
        let center_pad = "   ";
        loop {
            match (logo_lines.next(), info_lines.next()) {
                (Some(logo_line), Some(info_line)) => 
                    writeln!(f, "{}{}{:^}", logo_line, center_pad, info_line)?,
                (Some(logo_line), None) => 
                    writeln!(f, "{}", logo_line)?,
                (None, Some(info_line)) =>
                    writeln!(f, "{:<width$}{}{:^}", "", center_pad, info_line, width = logo_lines.width())?,
                (None, None) => { writeln!(f, "\n")?; break },
            }
        };
```

**Comment by andymac-2** [comment]
Oh whoops, that was definitely a victim of a large merge. Those commits occurred while I was moving things to different modules. As far as I can tell there are no other changes that were rolled back.

**Comment by o2sh** [comment]
No problem, merges are the worst.

Plz push the correction when possible.

**Pull request merged**
