### PR TITLE
🎄Merry Christmas and Thanks! 💕

### PR DESCRIPTION
**Pull request by o2sh**
I just wanted to take this moment and say 'Thank You' to everyone who contributed to this project and helped Onefetch grow and be what it is today.

thanks

<p align="center">:heart::heart:</p>

------
@spenserblack, @Luke-zhang-04, @ZapAnton, @yoichi, @HallerPatrick, @CephalonRho, @atluft, @andymac-2, @ccmetz, @Phundrak, @maash3r, @rogercyyu, @ktsuench, @ebroto, @Sh3mm, @Kloenk, @pablodiegoss, @xynxynxyn, @axdiamond, @Emanon42, @geeseven, @goosedb, @aluft-logi, @Ferryistaken, @KaindlJulian, @nguyenquannnn, @JoshBrudnak, @rootEnginear, @cnsumner, @rockisch, @vypxl, @zxey, @astynax, @akrantz01, @erikgaal, @KasraF, @MarkusPettersson98, @nikofil, @hoop33, @MaxJohansen, @reime005, @di-wu, @Cogitri, @SamTebbs33, @SuperSandro2000, @CodeLongAndProsper90, @Vipul-Bajaj, @WillyChen123, @rtroxler, @viniciusestevam, @tacrazymage, @aeter, @popey, @amiralies, @bojan88, @jadijadi, @jephthai, @tianlangwu, @kitlith

### CODE REVIEW

**Comment by maash3r** [comment]
A Merry Christmas to you too @o2sh 
This was kinda my first time contributing on GitHub, feels so good to be part of something.

**Comment by ktsuench** [comment]
Happy holidays to @o2sh and all 🎄🎉, it was my first time contributing too :) Positive experience, thanks for the opportunity!

**Comment by HallerPatrick** [comment]
Thank you very much @o2sh, I also really enjoy working on onefetch and you.

Should this PR be merged, if yes I will gladly do this :)

**Comment by o2sh** [comment]
> Should this PR be merged, if yes I will gladly do this :)

Sure, go ahead :+1:

**Comment by SamTebbs33** [comment]
Merry Christmas! It was a pleasure contributing to such a great piece of software.

**Pull request merged**
