### PR TITLE
Add changes line

### PR DESCRIPTION
**Pull request by axdiamond**
This addresses #165 

Onefetch will now show a changes line when there are uncommitted changes in the repo!

Basically, it takes the output of `git diff --shortstat HEAD`, and replace the text with appropriate symbols. 

    files changed into +-
    insertions(+) into +
    deletions(-) into -

### CODE REVIEW

**Comment by o2sh** [comment]
Thanks a lot for your contribution @axdiamond 

Few remarks:
* I think it would be better to call it `Pending` instead of `Changes`, to let the user know that this are only uncommited changes + it prevents having to treat singular/plural cases --> `Change(s)`
* About the positioning, maybe place it just below `HEAD`
* You are mixing information at line level (`insertion(s)(+)`, `deletion(s)(-)`) with information at file level (`file(s) changed`), maybe `git diff ---shortstat` is not the right command for the job...We only want **file level infos** for now, `git status` shows it pretty well.

Looking forward to merge your PR :+1:

**Comment by axdiamond** [comment]
@o2sh I did the other changes, but I'm not sure how to get lines changed from git.

git status only shows files modified, not lines. 

Do you have any suggestions on how I should get the lines changed?

**Comment by o2sh** [comment]
> git status only shows files modified, not lines.

That's right, we are only interested in file level changes.

**Comment by axdiamond** [comment]
Ooooohhh I'm a silly goose. 

How does it look now?

**Comment by axdiamond** [comment]
I'm new to rust btw, so any nitpicking is welcome!

**Comment by o2sh** [comment]
I detected one missing checks --> `"A" | "AM" |"??" => added += 1`, (AM)

---

if one of these 
```
let mut deleted = 0;
let mut added = 0;
let mut modified = 0;
```
remains equal to zero, it shouldn't be shown in the result.

---

> I'm new to rust btw, so any nitpicking is welcome!

LGTM, @spenserblack did I miss smth?

**Comment by o2sh** [comment]
if (modified == 0 || modified && added ==  0) , you get a leading whitespace --> I'll trim the result.

---
Thanks a lot for your help @axdiamond , your contribution is very much appreciated  :1st_place_medal:

**Pull request merged**
