### PR TITLE
Added HolyC support

### PR DESCRIPTION
**Pull request by Ferryistaken**
The logo is just like the C logo but with a cross, and with TempleOS colors

### CODE REVIEW

**Comment by o2sh** [comment]
Thanks for your PR @Ferryistaken 
Still, your design feels too similar with the C logo.

Maybe try converting this one:

holyc

Looking forward to merge your PR :100:

**Comment by Ferryistaken** [comment]
Ok I'll work on that! I saw that one while searching for a holyc logo but I liked the one with the cross better

**Comment by Ferryistaken** [comment]
New logo is here! Here is how it looks with my terminal colorscheme:
https://imgur.com/a/FXn8gDD

The color of the cirle on top is yellow, the top part of the C logo is cyan, and the bottom is Blue

**Comment by Ferryistaken** [comment]
Nevermind by taking the picture I realized that now that I added the colors it's not centered anymore. I'm gonna work on that now

**Comment by Ferryistaken** [comment]
The CI/CD build fails, but it compiles perfectly on my Arch Linux system?

**Comment by o2sh** [comment]
> 
> 
> The CI/CD build fails, but it compiles perfectly on my Arch Linux system?

From CI:

```
 ---- onefetch::language::ascii_size::holyc_height stdout ----
thread 'onefetch::language::ascii_size::holyc_height' panicked at 'assertion failed: `(left <= right)`
  left: `28`,
 right: `25`: holyc.ascii is too tall.', src/onefetch/language.rs:166:1
```

Which means that your logo exceeds max-height by 3. Indeed, from [CONTRIBUTING.md](https://github.com/o2sh/onefetch/blob/master/CONTRIBUTING.md):

> * Your ascii logo's dimensions must fall below 25x40. The CI will fail otherwise.

**Comment by Ferryistaken** [comment]
Ok I'll try and create a new one when I have time but as you have probably figured out making ascii logos isn't the thing i'm best at(nor something that I really like doing)

**Comment by o2sh** [comment]
> Ok I'll try and create a new one when I have time but as you have probably figured out making ascii logos isn't the thing i'm best at(nor something that I really like doing)

I agree, it can be quite frustrating after a while. But you're very close, try using the [python tool](https://github.com/o2sh/onefetch/wiki/image-to-ascii) to generate a smaller C logo.

**Comment by Ferryistaken** [comment]
Will do thanks for the pointer

**Comment by FlexCode29** [comment]
Immediately merge u heretic freaks

**Comment by o2sh** [comment]
> Immediately merge u heretic freaks

The day of _merge_ has been announced and it will come :raised_hands: . But the day has not come yet.

...soon :pray:

**Comment by DanteFalzone0** [comment]
Why not just use the TempleOS logo?

Something like this:
image

Or this:
image

but asciified?

**Comment by o2sh** [comment]
I don't think we should confuse the programming language with the operating system. The TempleOS ASCII logo would be relevant in regard to Neofetch, not Onefetch.

**Comment by Ferryistaken** [comment]
Well AFAIK there is not official Holy C logo, so he isn't wrong

**Comment by o2sh** [comment]
Ok, I surrender. @Ferryistaken feel free to switch to the TempleOS design if you prefer.

**Comment by Ferryistaken** [comment]
I like the one you proposed more, I was just saying that since there is no official logo it technically wouldn't be wrong to use the TempleOS logo. BTW I think that I will have time this weekend, so at most the pull request will be ready for sunday

**Comment by Ferryistaken** [comment]
The only change that I would make now is maybe make the C part of the logo look more like the `resources/c.ascii` logo, but I like the more "rough" aesthetic, I think it fits the language(and templeOS)

**Comment by o2sh** [comment]
Thanks for you PR @Ferryistaken, I cleaned it a bit:

holyc

**Comment by Ferryistaken** [comment]
Looks very nice! Sorry that you couldn't use my design and that this whole PR was a bit useless, I'll try and do better if I'll ever add new languages!

**Comment by o2sh** [comment]
Final version:

holyc

**Pull request merged**
