### PR TITLE
Allow custom colors via CLI

### LINKED ISSUE #69: Set Custom colors via flag
Currently, the colors used for each language are hard coded in a vector:
`Language::Clojure => vec![Color::BrightBlue, Color::BrightGreen]`

We would like to give the user the possibility to set his own colors by passing a flag:

`onefetch --ascii_colors 1 2 3 4 5 6`

Inspired from a neofetch's [feature](https://github.com/dylanaraps/neofetch/wiki/Custom-Ascii-art-file-format) , it would be helpful to add a visual marker at the bottom right to tell the user the color order (1: red, 2: green...) as such :

DeepinScreenshot_select-area_20191012000557

This feature is for the brave only :1st_place_medal:

### PR DESCRIPTION
**Pull request by spenserblack**
Fixes #69 
Might also help with #33 :thinking: 

The formatting of these changes are kind of ugly, please let me know if you want any changes to code format :smiley:.

### `onefetch -h`
help
*There is a `0` option, but it's invisible due to black background*

### CODE REVIEW

**Comment by o2sh** [comment]
This is great @spenserblack 
I think it solves #33 too.

You just need add a visual marker, something like (or else if you have a better idea) -->

DeepinScreenshot_select-area_20191013213518

Looking forward to merge your PR

**Comment by spenserblack** [comment]
Just the 8 colors (Black - White), or also the bright versions of those colors?

**Comment by o2sh** [comment]
I would say the more better as long as it doesn't take too much space...

**Comment by spenserblack** [comment]
How does this look?
screen

**Comment by o2sh** [comment]
LGTM :1st_place_medal:

**Pull request merged**
