### PR TITLE
#233 Update Go ascii art

### PR DESCRIPTION
**Pull request by nguyenquannnn**
#233 Screenshot!
image

Go official logo is acutally very well done imo

### CODE REVIEW

**Comment by o2sh** [comment]
Hi @nguyenquannnn, 

This is indeed a big improvement compared to the previous one.

But based on what you've shown to be capable of with the Rust logo, I'm sure you can do better.

You can either stick with this design and clean it a little. Or go for their mascot:



----------
Useful, [Ascii Art From Image File Using Python Image Library](https://github.com/o2sh/onefetch/wiki/ASCII-Art-From-Image-Using-Python-Image-Library) by @atluft

**Comment by nguyenquannnn** [comment]
image

Here's another design with their mascot

**Comment by o2sh** [comment]
Yes!! :heart: 

I couldn't help but adding a third color:

go

This is perfect, thanks a lot @nguyenquannnn

**Comment by nguyenquannnn** [comment]
> Yes!! :heart: 
> 
> 
> 
> I couldn't help adding a third color:
> 
> 
> 
> go
> 
> 
> 
> This is perfect, thanks a lot @nguyenquannnn 
> 
> 
Haha looks good!

**Pull request merged**
