### PR TITLE
fixes #220

### LINKED ISSUE #220: Reduce size of Swift's ASCII logo
Some of our ASCII logos exceed the max size imposed by our [Guideline](https://github.com/o2sh/onefetch/blob/master/CONTRIBUTING.md#ascii-logo). The Swift's ASCII logo is one of them:

swift

The idea would be to come up with a new ASCII logo for Swift with a width < MAX_WIDTH = 40 and height < MAX_HEIGHT = 25

-----

To check if your ASCII logo falls into the boundaries of width/height defined above, you can run `cargo test -- --ignored`

### PR DESCRIPTION
**Pull request by atluft**
Using https://www.ascii-art-generator.org/ to create ASCII art.
```
gsed 's/M/ /g' ~/Downloads/banner.txt > resources/swift.ascii 
gsed -i 's/ *$//g' resources/swift.ascii
gsed -i 's/^/{0}/' resources/swift.ascii
```

### CODE REVIEW

**Comment by o2sh** [comment]
Hi @atluft, looks great!
But maybe, we could try and make it look less "bulky".

For example, some retouching (by hand) can be done on the wings to make them a little more pointy. You could also increase the space between the two middle wings like in the original logo's design. 

I know it's not easy, especially considering the max-width of 45.

Looking forward to merge your PR.

**Comment by atluft** [comment]
Agree, also I would like to provide some python code I used to adjust to your advice. Do you have a preferred utils or tools directory to create / update?

Here is new swift output:
image

**Comment by o2sh** [comment]
You nailed it! it's perfect.

> Do you have a preferred utils or tools directory to create / update?

Not really, I usually start the same way you did; by using an online tool and then retouching by hand.

> Agree, also I would like to provide some python code I used to adjust to your advice. 

That would be much appreciated. Maybe you could add an entry in the [wiki](https://github.com/o2sh/onefetch/wiki) to which we can point to in the [How to add support for a new language](https://github.com/o2sh/onefetch/blob/master/CONTRIBUTING.md#adding-support-for-a-new-language)

**Comment by atluft** [comment]
Good idea, added link [here](https://github.com/o2sh/onefetch/pull/224/commits/cfbd0e26e2136ccf37109af7e8b9f0fa70c9a633)

Added the wiki page [Ascii Art From Image File Using Python Image Library](https://github.com/o2sh/onefetch/wiki/ASCII-Art-From-Image-Using-Python-Image-Library)

Also added link on Home page [Home](https://github.com/o2sh/onefetch/wiki), not sure how wiki pages get organized on the right hand side of the screen there.

**Comment by o2sh** [comment]
Impressive stuff @atluft 

Hopefully, this won't be your last contribution. Thanks again :+1:

**Pull request merged**
