### PR TITLE
Added repository name and url detection

### PR DESCRIPTION
**Pull request by JoshBrudnak**
Added repository name and url detection by parsing the repositories remote url. I also formatted the code using rustfmt.
This resolves the url and name part of #9

### CODE REVIEW

**Comment by zxey** [comment]
Just a heads up, this may make it harder for people with macOS to build this project, because of the added git2 dependency, you might need to add 'default-features = false' which will disable some optional features of git2 (amongst them is ssh feature, which is the part that makes it harder to build for macOS), you can check more in git2-rs repository readme [here](https://github.com/alexcrichton/git2-rs#building-on-osx-1010).

This is one of the reason why I chose to call git command directly in #12. But if this is merged, we can change how authors are detected too.

Also will the repo url get correctly recognized if user tracks upstream or origin with ssh instead of https?

**Comment by JoshBrudnak** [comment]
Yes, it will work with ssh and https. Thanks.

**Comment by o2sh** [comment]
Good job @JoshBrudnak, but the way you detect the repo name relies on the presence of `.git` in the url. So, if I choose to clone a repo without it:

`git clone https://github.com/o2sh/onefetch`

It won't work...

**Comment by JoshBrudnak** [comment]
Good point, In that case I'll assume the repository name is the last part of the url. :+1:

**Comment by o2sh** [comment]
Thanks a lot @JoshBrudnak, @zxey what do we do for the author detection ? do we maintain what we have, or do we use git2-rs ?

We're almost there, only the License is left hardcoded.

**Pull request merged**
