### PR TITLE
Improve code coverage of src/info/repo/contributors.rs

### PR DESCRIPTION
**Pull request by alessandroasm**
Part of task https://github.com/o2sh/onefetch/issues/700

### CODE REVIEW

**Review by spenserblack — APPROVED** [review]

**Review by Byron — APPROVED** [review]
I'd not be the best choice in reviewer for anything that doesn't touch `gitoxide`, but LGTM.

**Comment by spenserblack** [comment]
@Byron I think it just happens automatically because of this:
https://github.com/o2sh/onefetch/blob/c88541d3162e32119ba0805e312e17382fb1c4b5/.github/CODEOWNERS#L4

Should the definition be changed?

**Comment by Byron** [comment]
Thanks for clarifying! It's interesting that the messaging around this that originates from GitHub is ambiguous at best or even misleading:

> @alessandroasm requested your review on: https://github.com/o2sh/onefetch/pull/814 Improve code coverage of src/info/repo/[contributors.rs](http://contributors.rs/) as a code owner.

To me it really seems that alessandroasm triggered it intentionally even though it's happening automatically.

@spenserblack, if you see a way to narrow the code-ownership to files that deal with `gitoxide` that would be appreciated, but it wouldn't be a big deal to leave it as is either. Thank you.

**Comment by alessandroasm** [comment]
@Byron I didn't request a review manually, I think the repo is configured to automatically do that. :)

**Pull request merged**
