### PR TITLE
feat(languages): add support for JSX and TSX

### PR DESCRIPTION
**Pull request by Luke-zhang-04**
Small changes for JSX and TSX

### CODE REVIEW

**Comment by Luke-zhang-04** [comment]
TSX
image
JSX
image

Not sure about the colours for JSX. Maybe yellow fits better since it's Javascript?

**Comment by Luke-zhang-04** [comment]
oOf looks like I'll have to fix the ascii art tomorrow

**Comment by Luke-zhang-04** [comment]
image

**Comment by o2sh** [comment]
Looks great @Luke-zhang-04 
Unless you're not done, make your PR "Ready for review" and I'll merge it.

**Comment by Luke-zhang-04** [comment]
Oops

**Pull request merged**
