### PR TITLE
Ascii for Prolog 

### PR DESCRIPTION
**Pull request by GooseDB**

### CODE REVIEW

**Comment by o2sh** [comment]
< I'm sure you can do better than that >
 --------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

**Comment by GooseDB** [comment]
Do you mean I should remake this with other symbols or choose another logo?

**Comment by o2sh** [comment]
be creative, we already have toot many ascii logos that look alike, which are basic online conversion from PNG

**Comment by GooseDB** [comment]
Hey, @o2sh.  Why did close this PR? Sorry for the silence. I just had no time to answer. I've updated ASCII with the logo formed of Prolog programs ( probably broken while shaping but who cares :) ). What do you think about it?

**Comment by spenserblack** [comment]
Just checked out your new commit. Making ASCII art out of Prolog code is a pretty cool idea :+1:.
Looks like you're sticking with plain white. Any chance of adding a bit more color?
I'll reopen this PR, since you're still working on it, @GooseDB.

P.S. Have fun fixing merge conflicts :rofl:

**Comment by GooseDB** [comment]
изображение

**Comment by o2sh** [comment]
Looks great @GooseDB 

Thanks for your contribution :1st_place_medal:

**Pull request merged**
