### PR TITLE
Feature/no merges

### LINKED ISSUE #131: Onefetch counts Merge Commits
Think that it's not ok to count merge commits since they are with no value at all and it makes wrong statistics.

### PR DESCRIPTION
**Pull request by spenserblack**
Resolves #131 
Let me know if I missed anything!

### CODE REVIEW

**Comment by o2sh** [comment]
Looks great :+1: , If you could just add a `.short("n")` as a shortcut for `--no-merges`

**Comment by spenserblack** [comment]
:+1:, but are we sure `-n` should be used for this? There's already a "no" flag (`-n`, `--no-bold`). How about `.short("m")`?

**Comment by o2sh** [comment]
You're absolutely right, it's more consistent that way :+1:

**Comment by spenserblack** [comment]
Done :smiley:

**Pull request merged**
