### PR TITLE
Add Zig support

### PR DESCRIPTION
**Pull request by SamTebbs33**
This patch adds support for [Zig](https://github.com/ziglang/zig). Unfortunately colored doesn't support orange.

onefetch with Zig

### CODE REVIEW

**Comment by o2sh** [comment]
Nice to see you took advantage of the multicolor feature for the ascii logo.
Unfortunately, it looks a little noisey and unpolished.

You're almost there.

Looking forward to merge your PR :100:

**Comment by SamTebbs33** [comment]
Thanks for the feedback @o2sh . I agree that it looked unpolished, so I chose to replace all the white symbols with Zs. Let me know if it's more suitable or if I should go back to the style with varied characters.

v2

**Comment by o2sh** [comment]
Better! @SamTebbs33 
Try and replace the "Z"s with blank spaces and the "/" with a more visble character (#, $...)

**Comment by SamTebbs33** [comment]
Much better :)
v3

**Pull request merged**
