### PR TITLE
Add FSharp support

### PR DESCRIPTION
**Pull request by Emanon42**

### CODE REVIEW

**Comment by o2sh** [comment]
Nice to see you took advantage of the multicolor feature for the ascii logo.
Unfortunately, it looks a little noisey and unpolished.

Looking forward to merge your PR 💯

**Comment by Emanon42** [comment]
I change the ascii. How about now?

**Comment by o2sh** [comment]
Looking much better @Emanon42 

Few remarks:

* The first color has to be {0} and not {1}
* To better match the real logo, you should use two colors, Color::BrightBlue for the first half and Color:Cyan for the second

Looking forward to merge your PR

**Comment by Emanon42** [comment]
As your suggests!

**Pull request merged**
