### PR TITLE
Improve code coverage of src/info/repo/commits.rs

### PR DESCRIPTION
**Pull request by alessandroasm**
Part of task #700

### CODE REVIEW

**Comment by alessandroasm** [comment]
Not sure why Github is showing this as a full rewrite of the file :(

**Comment by spenserblack** [comment]
>Not sure why Github is showing this as a full rewrite of the file :(

Did the line endings change? LF to CRLF? Not sure which editor you use, but it will likely show you if you're using Unix/LF or Windows/Dos/CRLF.

**Comment by alessandroasm** [comment]
Great, I'm gonna wait until #815 gets merged and then I'll update / rebase this if needed. Thank you @spenserblack

**Comment by spenserblack** [comment]
Thanks @alessandroasm! If you feel comfortable rebasing onto `main` then can you please do so?
There's a good chance that this might be squash-merged, so a normal merge commit is fine, too.

**Comment by spenserblack** [comment]
P.S. `git checkout --ours` and `git checkout --theirs` are useful when resolving these full-file conflicts.

**Comment by alessandroasm** [comment]
Thanks for all the help @spenserblack! It should be OK now :+1: 

Please let me know if there's anything else I could improve.

**Review by spenserblack — APPROVED** [review]
This diff looks much better :smile:

**Pull request merged**
