### PR TITLE
add option to change character set

### PR DESCRIPTION
**Pull request by geeseven**
```console
$ tools/image_to_ascii.py -f ../GraphQL_Logo.svg.png
                     :::                     
                   :::::::                   
                   :::::::                   
                 :::::::::::                 
              :::: ::::::: ::::              
     ::::  ::::   ::     ::   ::::  ::::     
   :::::::::     ::       ::     :::::::::   
   ::::::::     ::         ::     ::::::::   
   :::::::     ::           ::     :::::::   
     :::      ::             ::      :::     
      ::     ::               ::     ::      
      ::    ::                 ::    ::      
      ::   ::                   ::   ::      
      ::  ::                     ::  ::      
      :: ::                       :: ::      
     :::::                         :::::     
   :::::::                         :::::::   
   :::::::::::::::::::::::::::::::::::::::   
   :::::::::                     :::::::::   
     ::::  ::::               ::::  ::::     
              ::::   :::   ::::              
                 ::::::::::                  
                   :::::::                   
                   :::::::                   
                     :::

$ tools/image_to_ascii.py -f ../GraphQL_Logo.svg.png -c " $"
                     $$$                     
                   $$$$$$$                   
                   $$$$$$$                   
                 $$$$$$$$$$$                 
              $$$$ $$$$$$$ $$$$              
     $$$$  $$$$   $$     $$   $$$$  $$$$     
   $$$$$$$$$     $$       $$     $$$$$$$$$   
   $$$$$$$$     $$         $$     $$$$$$$$   
   $$$$$$$     $$           $$     $$$$$$$   
     $$$      $$             $$      $$$     
      $$     $$               $$     $$      
      $$    $$                 $$    $$      
      $$   $$                   $$   $$      
      $$  $$                     $$  $$      
      $$ $$                       $$ $$      
     $$$$$                         $$$$$     
   $$$$$$$                         $$$$$$$   
   $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$   
   $$$$$$$$$                     $$$$$$$$$   
     $$$$  $$$$               $$$$  $$$$     
              $$$$   $$$   $$$               
                 $$$$$$$$$$                  
                   $$$$$$$                   
                   $$$$$$$                   
                     $$$

$ tools/image_to_ascii.py --help
usage: image_to_ascii.py [-h] [-c CHARACTERS] -f FILE [-r height width] [-s] [-v]

convert an image file to ASCII art

optional arguments:
  -h, --help            show this help message and exit
  -r height width, --resolution height width
                        set custom resolution, default 25 45
  -s, --save_image      optionally save ASCII to image file
  -v, --version         show version

required argument:
  -c CHARACTERS, --characters CHARACTERS
                        characters available to be used, default " .:_-"
  -f FILE, --file FILE  image file to convert to ASCII
```

### CODE REVIEW

**Comment by HallerPatrick** [comment]
Is this part of an issue? If not, it is a good idea to first go through the approval/discussion phase in an Issue. :)

**Comment by geeseven** [comment]
The CONTRIBUTING.md file states:

You open an issue to discuss any significant work - we would hate for your time to be wasted.

This took two minutes and is straight forward.  I really do not foresee any discussion regarding this change and if there is it can happen here.

**Comment by o2sh** [comment]
Yeah, for this kind of small PR: not having a linked issue is no problem at all  :ok_hand:

Thanks a lot for improving the script @geeseven

**Comment by HallerPatrick** [comment]
> The CONTRIBUTING.md file states:
> 
> You open an issue to discuss any significant work - we would hate for your time to be wasted.
> 
> This took two minutes and is straight forward. I really do not foresee any discussion regarding this change and if there is it can happen here.

I am sorry. I never worked not the ascii art part, so I was not into the contribution guidelines for this. This is purely my fault. Sorry

**Pull request merged**
