### PR TITLE
Fixed ascii art widths.

### LINKED ISSUE #93: [Pre-procesing]Keep the same spacing between the ASCII art and the info lines
As of today, the distance/spacing between the ASCII logo and the info bloc is quite inconsistent among the different languages:

* Perl (too much spacing and presence of left indentation):

61182863-f91f6e00-a628-11e9-9856-8e9b3e1b928f

* Swift (no spacing and left indentation):
 
56481406-0a088980-64e9-11e9-9e81-09f00b2414cb

The idea would be too have the same spacing for all and no left indentation (and no top/bottom empty lines).

**It has to be a code base solution, some kind of pre-processing of the ascii files in rust. So that we won't have to retouch by hand every art that will be submitted/done in the future.**

:100:  :1st_place_medal:

### PR DESCRIPTION
**Pull request by andymac-2**
- Create parse module
- Simple parser for *.ascii format
- AsciiArt struct allows for correcting the width to remove spacing on the left and right.
- default spacing of 1 character between the logo and the info

Fixes #93

### CODE REVIEW

**Comment by o2sh** [comment]
Very impressive @andymac-2 !

Few remarks:

* The logo used to be displayed in bold, I don't think it's the case anymore.
* Yon don't seem to have gotten rid of the top/bottom spacing for the logo.

Looking forward to merge your PR :1st_place_medal: 

Your help would be much appreciated in #97

**Comment by andymac-2** [comment]
These issues have now been fixed!

Before (current master): extra line at the bottom, spacing on the right
Screen Shot 2019-10-20 at 7 20 24 pm

After (lines removed, colums adjusted, text emboldened):
Screen Shot 2019-10-20 at 7 09 42 pm

**Comment by o2sh** [comment]
Amazing job @andymac-2 

plz take a shot at #97

**Comment by o2sh** [comment]
@andymac-2 you seem to have forgotten to update the test after switching to bold (added`1;` ANSI escape character) -->

        **assert_eq!(
            Tokens("     ").render(&colors_shim, 0, 0),
            "\u{1b}[1;37m\u{1b}[0m"
        );**

which makes me think of #99, the test will have to take that new flag into account...

Still amazing Job!!

**Pull request merged**
