### PR TITLE
 Refactoring of package manager module

### PR DESCRIPTION
**Pull request by o2sh**
With this PR, I introduced the `define_package_managers!` macro making it easier to add support for a new package manager.

However, it doesn't handle #347 where you have multiple parsers per package manager.

### CODE REVIEW

**Comment by o2sh** [comment]
43206c4 seems to cover #347

**Review by HallerPatrick — APPROVED** [review]
Tested all changes on various repos and it yields the expected behaviour. Code wise there are no logical changes except the macro, which looks good to me.

**Comment by HallerPatrick** [comment]
> [43206c4](https://github.com/o2sh/onefetch/commit/43206c42648db9f7879dde909a296446e3ca0268) seems to cover #347

I will close #347

**Review by spenserblack — APPROVED** [review]
LGTM :+1:

This looks much cleaner with the macro :smile:

**Pull request merged**
